dist: bionic
addons:
  apt:
    packages:

language: cpp
compiler: clang
script:
        - cmake ./
        - cmake --build ./ --target package
deploy:
        file: "${TRAVIS_BUILD_DIR}/descriptor.json"
        provider: bintray
        user: ${BINTRAY_USER}
        key: ${BINTRAY_API_KEY}
        skip_cleanup: true

